name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux-i386:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build linux-i386
      run: |
        scripts/build-ubuntu-i386.sh

  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh

  build-android-armv7a:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug
        ./waf.bat build

  build-dedicated-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build

  build-dedicated-linux-i386:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build dedicated linux-i386
      run: |
        scripts/build-ubuntu-i386.sh -d

  build-dedicated-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build dedicated linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh -d
